
# Tell pre-commit how to run hook
- id: remove-empty-cells
  name: Remove Empty Jupyter Cells
  description: Remove empty code and markdown cells from Jupyter notebooks before committing
  entry: python3 -m remove_empty_cells.cli
  language: python
  types: [jupyter]
  files: \.ipynb$
